version: "2"

# golangci-lint configuration
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unparam
    - unconvert
    - goconst
    - gocyclo
    - bodyclose
  settings:
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
  exclusions:
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      # Exclude long lines in go:generate
      - linters:
          - lll
        source: "^//go:generate "

run:
  tests: true
