# golangci-lint configuration
version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unparam
    - unconvert
    - goconst
    - gocyclo
    - bodyclose
  settings:
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      # Exclude long lines in go:generate
      - linters:
          - lll
        source: "^//go:generate "

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true
