version: 2
project_name: kopilot

before:
  hooks:
    - go mod tidy

builds:
  - id: kopilot
    main: .
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildDate={{.Date}}
      - -X main.gitCommit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

sboms:
  - artifacts: archive

checksum:
  name_template: "checksums.txt"

signs:
  - cmd: cosign
    args:
      - sign-blob
      - --yes
      - --output-signature=${signature}
      - --output-certificate=${certificate}
      - ${artifact}
    artifacts: checksum

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'Merge pull request'
      - 'Merge branch'
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Performance Improvements
      regexp: '^perf:'
      order: 2
    - title: Refactors
      regexp: '^refactor:'
      order: 3
    - title: Other Changes
      order: 999

brews:
  - repository:
      owner: e9169
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/e9169/kopilot
    description: "Kubernetes Cluster Status Agent powered by GitHub Copilot"
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "kopilot"
    test: |
      system "#{bin}/kopilot", "--version"
