// Code generated by copilot-sdk bundler; DO NOT EDIT.

package main

import (
	"bytes"
	"io"
	"encoding/base64"
	_ "embed"

	"github.com/github/copilot-sdk/go/embeddedcli"
	"github.com/klauspost/compress/zstd"
)

//go:embed zcopilot_0.0.409_darwin_arm64.zst
var localEmbeddedCopilotCLI []byte

//go:embed zcopilot_0.0.409_darwin_arm64.license
var localEmbeddedCopilotCLILicense []byte


func init() {
	embeddedcli.Setup(embeddedcli.Config{
		Cli: cliReader(),
		License: localEmbeddedCopilotCLILicense,
		Version: "0.0.409",
		CliHash: mustDecodeBase64("W4dzd4gskdxUEhNxpdh52piUEHZtVKzrIxfeuz5zCBw="),
	})
}

func cliReader() io.Reader {
	r, err := zstd.NewReader(bytes.NewReader(localEmbeddedCopilotCLI))
	if err != nil {
		panic("failed to create zstd reader: " + err.Error())
	}
	return r
}

func mustDecodeBase64(s string) []byte {
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		panic("failed to decode base64: " + err.Error())
	}
	return b
}
