source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-theme-cayman"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]
